/**
 * Die Technical Sheet Report Generator
 * 
 * Generates a PDF technical sheet for a die using pdf-lib.
 * All data comes from real persisted records — no fabricated values.
 * Absent fields display "Not Captured" labels.
 */

import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib/cjs";

const ORANGE = rgb(0.98, 0.45, 0.09);
const DARK = rgb(0.07, 0.09, 0.13);
const TEXT = rgb(0.07, 0.09, 0.13);
const LIGHT_GRAY = rgb(0.96, 0.97, 0.98);
const WHITE = rgb(1, 1, 1);
const PAGE_WIDTH = 595.28;
const PAGE_HEIGHT = 841.89;
const MARGIN = 40;

function sanitize(text: string | null | undefined): string {
  if (!text) return "Not Captured";
  return text.replace(/[^\x00-\xFF]/g, "");
}

function val(v: any, suffix = ""): string {
  if (v === null || v === undefined || v === "") return "Not Captured";
  return `${v}${suffix}`;
}

export type DieReportData = {
  company: { name: string; gst_number?: string };
  die: Record<string, any>;
  profile?: { profile_code?: string; profile_name?: string; section_weight_kg_per_m?: number } | null;
  customer?: { customer_name?: string; company_name?: string } | null;
  trials: Record<string, any>[];
  corrections: Record<string, any>[];
  nitridings: Record<string, any>[];
  generatedBy: string;
};

export async function buildDieTechnicalSheetPdf(data: DieReportData): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  let page: PDFPage = null!;
  let y: number = 0;

  function addPage() {
    page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    y = PAGE_HEIGHT - MARGIN;
    page.drawRectangle({ x: 0, y: 0, width: 14, height: PAGE_HEIGHT, color: ORANGE });
  }

  function text(str: string, x: number, yPos: number, font: PDFFont, size: number, color = TEXT) {
    page.drawText(sanitize(str), { x, y: yPos, font, size, color });
  }

  function sectionHeader(title: string) {
    y -= 25;
    page.drawRectangle({ x: MARGIN, y: y - 2, width: PAGE_WIDTH - MARGIN * 2, height: 18, color: LIGHT_GRAY });
    text(title, MARGIN + 8, y + 2, bold, 10, ORANGE);
    y -= 18;
  }

  function row(label: string, value: string) {
    if (y < 60) addPage();
    y -= 14;
    text(label, MARGIN + 8, y, regular, 8, rgb(0.4, 0.4, 0.4));
    text(value, MARGIN + 180, y, bold, 8);
  }

  addPage();

  // Header
  const bannerH = 50;
  page.drawRectangle({ x: MARGIN - 10, y: y - bannerH, width: PAGE_WIDTH - MARGIN + 10, height: bannerH, color: DARK });
  text("DIE TECHNICAL SHEET", MARGIN + 5, y - 32, bold, 16, WHITE);
  text(data.company.name, PAGE_WIDTH - MARGIN - 5 - bold.widthOfTextAtSize(data.company.name, 10), y - 32, bold, 10, ORANGE);
  y -= bannerH + 10;

  // Die identity
  sectionHeader("Die Identity");
  const d = data.die;
  row("Die Number", val(d.die_number));
  row("Die Code", val(d.die_code));
  row("Status", val(d.die_status));
  row("Type", val(d.die_type));
  row("Ownership", val(d.ownership_type));
  row("Cavities", val(d.number_of_cavities));
  row("Profile", data.profile ? `${data.profile.profile_code} · ${data.profile.profile_name}` : "Not Captured");
  row("Customer", data.customer?.company_name || data.customer?.customer_name || "Company owned");
  row("Priority", val(d.priority_level));

  // Geometry
  sectionHeader("Geometry & Design");
  row("Die Diameter", val(d.die_diameter_mm, " mm"));
  row("Die Thickness", val(d.die_thickness_mm, " mm"));
  row("Bearing Length", val(d.bearing_length_mm, " mm"));
  row("Extrusion Ratio", val(d.extrusion_ratio));
  row("CCD", val(d.ccd_mm, " mm"));
  row("Tongue Ratio", val(d.tongue_ratio));
  row("Output/Stroke", val(d.output_per_stroke_kg, " kg"));

  // Material
  sectionHeader("Material & Manufacturing");
  row("Steel Grade", val(d.die_steel_grade));
  row("Manufacturer", val(d.die_manufacturer));
  row("Cost", d.die_cost ? `₹${d.die_cost}` : "Not Captured");
  row("HRC", val(d.hrc_value));
  row("HV", val(d.hv_value));
  row("Heat Treatment", val(d.heat_treatment_status));

  // Performance
  sectionHeader("Performance");
  row("Total Production", d.total_production_kg ? `${d.total_production_kg} kg` : "Not Captured");
  row("Total Runs", val(d.total_runs));
  row("Recovery %", val(d.average_recovery_percent, "%"));
  row("Performance Grade", val(d.performance_grade));
  row("Last Used", val(d.last_used_date));

  // Footer
  y -= 30;
  text(`Generated by ${data.generatedBy} on ${new Date().toLocaleDateString("en-IN")}`, MARGIN, 25, regular, 7, rgb(0.5, 0.5, 0.5));
  text("ExtrusionOS Die Technical Sheet", PAGE_WIDTH - MARGIN - 150, 25, regular, 7, rgb(0.5, 0.5, 0.5));

  return pdf.save();
}
