import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { ReportModel } from "./builder";
import { escapeCsvCell, neutralizeSpreadsheetFormula } from "../../utils/csv.ts";

export type GeneratedReportFile = {
  bytes: Uint8Array;
  contentType: string;
  extension: "pdf" | "csv" | "xls";
};

function normalizeCell(value: unknown): string {
  return String(value ?? "").replace(/\r?\n/g, " ").trim();
}

function reportRows(model: ReportModel): string[][] {
  const rows: string[][] = [
    ["Report", model.header.reportTitle],
    ["Company", model.header.companyName],
    ["GST", model.header.companyGst],
    ["Module", model.header.moduleName],
    ["Record Number", model.header.recordNumber],
    ["References", model.header.references],
    ["Revision", model.header.revisionNumber],
    ["Generated Date", model.header.generatedDate],
    ["Generated By", model.header.generatedBy],
    ["Approval Status", model.header.approvalStatus],
    [],
  ];

  for (const section of model.sections) {
    rows.push([section.title]);
    rows.push(["Field", "Value"]);
    for (const field of section.fields) {
      rows.push([field.label, String(field.value)]);
    }
    rows.push([]);
  }

  return rows;
}

export async function generatePDF(model: ReportModel): Promise<GeneratedReportFile> {
  const pdf = await PDFDocument.create();
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const margin = 42;
  const lineHeight = 14;
  let page = pdf.addPage([595.28, 841.89]);
  let y = page.getHeight() - margin;

  function ensureSpace(lines = 1) {
    if (y - lines * lineHeight < margin) {
      page = pdf.addPage([595.28, 841.89]);
      y = page.getHeight() - margin;
    }
  }

  function draw(text: string, options: { size?: number; bold?: boolean; color?: ReturnType<typeof rgb> } = {}) {
    ensureSpace();
    page.drawText(text.slice(0, 110), {
      x: margin,
      y,
      size: options.size ?? 9,
      font: options.bold ? bold : regular,
      color: options.color ?? rgb(0.12, 0.12, 0.12),
    });
    y -= lineHeight;
  }

  draw(model.header.reportTitle, { size: 16, bold: true });
  draw(`${model.header.companyName} · GST: ${model.header.companyGst}`, { size: 10 });
  draw(`${model.header.moduleName} · ${model.header.recordNumber} · Rev ${model.header.revisionNumber}`, { size: 10 });
  draw(`Generated ${model.header.generatedDate} by ${model.header.generatedBy}`, { size: 9, color: rgb(0.38, 0.38, 0.38) });
  draw(`Approval: ${model.header.approvalStatus}`, { size: 9, color: rgb(0.38, 0.38, 0.38) });
  y -= 8;

  for (const section of model.sections) {
    ensureSpace(3);
    draw(section.title, { size: 12, bold: true });
    if (!section.fields.length) {
      draw("No captured fields for this section.", { color: rgb(0.45, 0.45, 0.45) });
      y -= 4;
      continue;
    }
    for (const field of section.fields) {
      draw(`${field.label}: ${field.value}`);
    }
    y -= 4;
  }

  return {
    bytes: await pdf.save(),
    contentType: "application/pdf",
    extension: "pdf",
  };
}

export function generateCSV(model: ReportModel): GeneratedReportFile {
  const csv = reportRows(model).map((row) => row.map((cell) => escapeCsvCell(normalizeCell(cell))).join(",")).join("\n");
  return {
    bytes: new TextEncoder().encode(csv),
    contentType: "text/csv;charset=utf-8",
    extension: "csv",
  };
}

export function generateExcel(model: ReportModel): GeneratedReportFile {
  const rows = reportRows(model)
    .map((row) => `<tr>${row.map((cell) => `<td>${neutralizeSpreadsheetFormula(normalizeCell(cell)).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")}</td>`).join("")}</tr>`)
    .join("");
  const htmlWorkbook = `<!doctype html><html><head><meta charset="utf-8" /></head><body><table>${rows}</table></body></html>`;
  return {
    bytes: new TextEncoder().encode(htmlWorkbook),
    contentType: "application/vnd.ms-excel;charset=utf-8",
    extension: "xls",
  };
}

export async function storeReport(
  supabase: { storage: { from: (bucket: string) => { upload: (path: string, bytes: Uint8Array, options: { contentType: string; upsert: boolean }) => Promise<{ error: { message: string } | null }> } } },
  file: GeneratedReportFile,
  storagePath: string,
  bucket = "reports"
): Promise<void> {
  const { error } = await supabase.storage.from(bucket).upload(storagePath, file.bytes, {
    contentType: file.contentType,
    upsert: true,
  });
  if (error) {
    if (/bucket not found/i.test(error.message) && bucket === "reports") {
      throw new Error("Report upload failed: missing private reports storage bucket. Apply migration 0059_reports_storage_bucket.sql.");
    }
    throw new Error(`Report upload failed: ${error.message}`);
  }
}
